### ISSUE TITLE
0.4 Update Breaks Quake 1's Music

### ISSUE THREAD

**Issue by OpenRift412** [dippy-dipper/cdaudio-winmm#3]
I don't know if this has to do with 0.4 having a 64-bit player executable, but for whatever reason, Quake (both GLQuake and software-rendered WinQuake executables) doesn't have music functionality anymore. It worked flawlessly before, but not anymore.

Also something to note: for some reason when starting either executable, there's a long hitching/freeze issue when the game tries to load a track.

Also, same exact problem with Hexen II, since that uses the exact same engine.

**Comment by dippy-dipper** [comment]
If you are using .mp3 or .wav files for music playback make sure the music folder is in the same directory as the cdaudioplr.exe. For example Quake\mcicda\music. The player no longer inherits it's working directory from the wrapper.

**Comment by OpenRift412** [comment]
Oh wow, that fixed all of it! Thanks!
