### ISSUE TITLE
Suggestion: Half-Life WON Support (1.0.1.6 and older)

### ISSUE THREAD

**Issue by OpenRift412** [dippy-dipper/cdaudio-winmm#8]
Been on a Half-Life binge lately and have been doing some experiments with the WON version. I'm aware that WON version 1.0.1.9 adds mp3 music functionality as an alternative, but there are features and quirks found in versions circa 1.0.1.6 that have been since broken with subsequent updates. So that being said, could you perhaps look into adding support for pre-mp3 patch Half-Life WON?

**Comment by dippy-dipper** [comment]
![HL-MCI-Error](https://user-images.githubusercontent.com/70149011/108107460-f0f6a280-7097-11eb-91e4-9f4c0b043484.png)

You mean this error message? It happens because the game tries to play the logo movie using MCI and the wrapper is not build to handle this. Later on the actual music should still work although it sparse and does not repeat. That is by game design though.

**Comment by OpenRift412** [comment]
> ![HL-MCI-Error](https://user-images.githubusercontent.com/70149011/108107460-f0f6a280-7097-11eb-91e4-9f4c0b043484.png)
> 
> You mean this error message?

What version was this taken in??

**Comment by dippy-dipper** [comment]
`What version was this taken in??`

I tested with the "Day one" demo that reports a version 1.0.0.1 and has a file date of September 27th 1998 for hl.exe. I also tested with the later "Uplink" demo version.

**Comment by OpenRift412** [comment]
I'm using v1.0.1.6 and winmm.dll doesn't recognize it at all.

**Comment by dippy-dipper** [comment]
A couple of questions / suggestions:

1. Is the game installed in a "normal" folder like C:\Games\Half-Life? Not on a network drive or some system protected folder like "Program files". One could also try starting the game with admin rights to make sure it is not an access permission issue.

2. Is the winmm.log being generated? If not then that means that the game is not loading the winmm.dll wrapper at start up.

3. Assuming winmm.log is not being generated is there any other software being used in the background that could be affecting the dll loading process? For example the _inmm wrapper has a nasty habit of changing the winmm.dll lookup to _inmm.dll and possibly editing some other calls too. You are not launching the game trough some front end like Steam?

4. In theory Windows could be configured to always load system dll files and ignore local files. For the off chance that this might be the case you could try to create an empty text document and name it "hl.exe.local" in the main game folder to force the Half-Life executable to look for dll files in the local directory first.

See:
https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-redirection

**Comment by OpenRift412** [comment]
> 1. Is the game installed in a "normal" folder like C:\Games\Half-Life? Not on a network drive or some system protected folder like "Program files". One could also try starting the game with admin rights to make sure it is not an access permission issue.

C:\Games\Half-Life is exactly where it's installed. Tried launching as admin, still no luck.

> 2. Is the winmm.log being generated? If not then that means that the game is not loading the winmm.dll wrapper at start up.

It's not. I've also tried running cdaudioplr.exe before launching the game and still nothing.

> 3. Assuming winmm.log is not being generated is there any other software being used in the background that could be affecting the dll loading process? For example the _inmm wrapper has a nasty habit of changing the winmm.dll lookup to _inmm.dll and possibly editing some other calls too. You are not launching the game trough some front end like Steam?

I did try _inmm at one point, but I made sure to switch back to the unpatched executable for testing with other wrappers. 

> 4. In theory Windows could be configured to always load system dll files and ignore local files. For the off chance that this might be the case you could try to create an empty text document and name it "hl.exe.local" in the main game folder to force the Half-Life executable to look for dll files in the local directory first.

Tried this as well, didn't work.

I think it could be related to the fact that Half-Life's engine is based on idtech 2, which has a substantial amount of code from Quake 2's iteration of the engine. Perhaps this quirk is something that the two games have in common?

**Comment by dippy-dipper** [comment]
> I think it could be related to the fact that Half-Life's engine is based on idtech 1, which has a substantial amount of code from Quake 2's iteration of the engine. Perhaps this quirk is something that the two games have in common?

It just doesn't make any sense to me why winmm.dll is not getting loaded. That should not depend on the wrapper. It is the game executable that loads the dll files from the game directory. Why would Quake2 and Half-Life refuse to load the winmm.dll on your system? And then again Quake1 seems to work just fine for you. It is bizarre.

It would be odd but I wonder if the dll file is being blocked by Windows security?

If you right click on the winmm.dll wrapper and open Properties in the General tab is there a text saying something like: 
"This file came from another computer and might be blocked to help protect this computer." 
If so then there should also be a button labeled "Unblock" next to it which should solve that issue.

Another thing that comes to mind could be some anti virus software which decides to interfere and block the dll from loading.

**Comment by OpenRift412** [comment]
Just checked it out and it just doesn't seem to be blocked. I use Windows Security, no antivirus software. Could it have to do with having a physical disc drive in my system? Nothing in it of course, but still.

**Comment by dippy-dipper** [comment]
> Could it have to do with having a physical disc drive in my system? Nothing in it of course, but still.

Nope, I have physical disc drives too and prefer to run all my games from the original discs. Main point of the cdaudio-winmm wrapper was to try and fix music playback from real physical mixed mode CD's running from real disc drives.

I am sorry, but I'm out of ideas as to what could cause the issues you are having. :-(
