### ISSUE TITLE
"CD is not present" error in GTA 1 if I use any winmm wrapper

### ISSUE THREAD

**Issue by BEENNath58** [dippy-dipper/cdaudio-winmm#9]
The game audio doesn't repeat under newer version of Windows so there is the need of using a winmm wrapper. Regardless of whatever wrapper I choose, the moment the game sees 'winmm.dll' in the directory it gives the "CD is not present error". The game music will repeat but you can't play the game because of the error. 

The same problem even exists with GTA London. The music repeats but you can't play the game. (help- gta london has a shorter music so if you want to check the problem GTA London music will save your time)

**Comment by dippy-dipper** [comment]
Testing GTA1 with [my ogg-winmm fork](https://github.com/dippy-dipper/ogg-winmm) seemed to work. The game relies on accurate track length/position data to verify the CD. Ripping the tracks from the original CD to .wav files and then converting those into .ogg files the track lengths were as follows:

Track02.ogg - 2:19
Track03.ogg - 7:27
Track04.ogg - 9:43
Track05.ogg - 9:39
Track06.ogg - 7:33
Track07.ogg - 11:01
Track08.ogg - 3:13
Track09.ogg - 8:47
Track10.ogg - 1:03
Track11.ogg - 1:12

**Comment by BEENNath58** [comment]
Than you very much. I tested the same thing out in GTA London and it also works fine. I also noticed that the in-game radio wouldn't repeat and the wrapper fixed the radio too.

**Comment by BEENNath58** [comment]
Now the game repeats the music in menu and also in the game radio. But when I exit the card and re enter it the radio doesn't continue but instead restart.
